---
title: "Simple document"
output: github_document
---

```{r}
library(tidyverse)
```

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv")
```

```{r}
names(litters_data)
```

```{r}
litters_data = janitor::clean_names(litters_data)
names(litters_data)
```

```{r}
view(litters_data)
```

```{r}
str(litters_data)
```

```{r}
head(litters_data)
```

```{r}
tail(litters_data)
```

```{r}
litters_data
```

```{r}
tail(litters_data, 5)
```

```{r}
skimr::skim(litters_data)
```

```{r}
view(litters_data)
```

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv",
  skip = 10, col_names = FALSE)
```

```{r}
head(litters_data)
```

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)
tail(litters_data)
```

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv",
  col_types = cols(
    Group = col_factor()
  )
)
head(litters_data)
```

```{r}
pups_data = read_csv("./data/FAS_pups.csv", col_types = "ciiiii")
skimr::skim(pups_data)
```

```{r}
library(readxl)
mlb11_data = read_excel("data/mlb11.xlsx", n_max = 20)
head(mlb11_data, 5)
```

```{r}
library(haven)
pulse_data = read_sas("./data/public_pulse_data.sas7bdat")
head(pulse_data, 5)
```

```{r}
pups_base = read.csv("./data/FAS_pups.csv")
pups_readr = read_csv("./data/FAS_pups.csv")
```

```{r}
View(pups_base)
View(pups_readr)

pups_base
pups_readr

pups_base$S
pups_readr$S
```











