---
title: "Data Manipulation"
output: github_document
---

```{r}
library(tidyverse)
```

Let's import the 'FAS_litters.csv' csv using a relative path.

```{r}
options(tibble.print_min = 3)

litters_df = read_csv("./data/FAS_litters.csv",
  col_types = "ccddiiii")
litters_df = janitor::clean_names(litters_df)

pups_df = read_csv("./data/FAS_pups.csv",
  col_types = "ciiiii")
pups_df = janitor::clean_names(pups_df)
```

# `select`


# Look at data

```{r}
litters_df
head(litters_df)
tail(litters_df)
```

You can use 'view'

```{r}
str(litters_df)

skimr::skim(litters_df)
```

## Options in `read_*`

```{r}
litters_df = read_csv("./data/FAS_litters.csv", skip = 10, col_names = FALSE)
```

Look at NA values.

```{r}
litters_df = read_csv("./data/FAS_litters.csv", na = c("NA", 19, "."))
```

# Column types

```{r}
litters_df = 
  read_csv(
    "./data/FAS_litters.csv",
    col_types = 
      cols(
        `GD0 weight` = col_character()
      ))
```

# Filter



# 'mutate'

This is used to add or change variables.


## `arrange`
















